ARG BASE_IMAGE

FROM $BASE_IMAGE

RUN	apk update && \
  apk upgrade && \
  apk add --update nginx && \
  rm -rf /var/cache/apk/*

COPY ./nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

ENTRYPOINT ["/usr/sbin/nginx", "-g", "daemon off;"]